// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignupAPI.Models;

namespace SignupAPI.Migrations
{
    [DbContext(typeof(SignupContext))]
    [Migration("20230311084929_GarageCustomer_CustomerVehicle")]
    partial class GarageCustomer_CustomerVehicle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SignupAPI.Models.CustomerVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("GarageBusinessCustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PreviousCustomerId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleFuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleMileage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VehicleMileageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNCTDue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleTaxDue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleTransmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GarageBusinessCustomerId");

                    b.ToTable("CustomerVehicle");
                });

            modelBuilder.Entity("SignupAPI.Models.GarageBusinessCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GarageBusinessId")
                        .HasColumnType("int");

                    b.Property<string>("GarageCustomerAddressline1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageCustomerAddressline2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageCustomerAddressline3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageCustomerAddressline4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageCustomerEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageCustomerForename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageCustomerMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageCustomerPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageCustomerPostcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageCustomerSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GarageBusinessCustomer");
                });

            modelBuilder.Entity("SignupAPI.Models.Garagebusiness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GarageAddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageAddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageAddressLine3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageAddressLine4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageBusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GarageMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaragePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Garagebusiness");
                });

            modelBuilder.Entity("SignupAPI.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Admin_owner")
                        .HasColumnType("bit");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GarageBusinessId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SignupAPI.Models.CustomerVehicle", b =>
                {
                    b.HasOne("SignupAPI.Models.GarageBusinessCustomer", null)
                        .WithMany("GarageCustomerVechicles")
                        .HasForeignKey("GarageBusinessCustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
